version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: go mod download
      - run: make
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
